backend:
  name: github
  repo: aldo-git-bit/aldo-git-bit.github.io
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - label: "Index Page"
        name: "index"
        file: "index.html"
        fields:
          - label: "HTML Source"
            name: "body"
            widget: "code"
            default_language: "html"
