backend:
  name: github
  repo: aldo-git-bit/aldo-git-bit.github.io
  branch: main
  auth_scope: repo

media_folder: "img"

collections:
  - name: "site"
    label: "Site Pages"
    files:
      - label: "Index"
        name: "index"
        file: "index.html"
        fields:
          - label: "HTML Source"
            name: "body"
            widget: "code"
            default_language: "html"
