backend:
  name: git-gateway
  branch: main

media_folder: "img"

collections:
  - name: "site"
    label: "Site Pages"
    files:
      - label: "Index"
        name: "index"
        file: "index.html"
        fields:
          - label: "HTML Source"
            name: "body"
            widget: "code"
            default_language: "html"
