backend:
  name: git-gateway
  branch: main

media_folder: "img"

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - label: "Index Page"
        name: "index"
        file: "index.html"
        fields:
          - label: "Main Content"
            name: "body"
            widget: "markdown"
